USE master
GO 
IF DB_ID('QLVEXE') IS NOT NULL 
	DROP DATABASE QLVEXE
GO
CREATE DATABASE QLVEXE
GO
USE QLVEXE 
GO

CREATE TABLE KHACHHANG
(

	MAKH CHAR(5),
	HOTEN NCHAR (50),
	GIOITINH BIT,
	DIENTHOAI CHAR(10),
	DIACHI NCHAR(50),
	EMAIL CHAR(20),

	CONSTRAINT PK_KHACHHANG 
	PRIMARY KEY(MAKH)
)
CREATE TABLE VEXE
(
	MAVE CHAR(10),
	GIAVE INT,
	BIENSOXE CHAR(10),
	SOGHE INT,
	NGAYDI DATE,
	THOIGIANDI CHAR(5),
	THOIGIANDEN CHAR(5),
	NOIDI NCHAR(20),
	NOIDEN NCHAR(20),
	MAKH CHAR(5),

	CONSTRAINT PK_VEXE PRIMARY KEY (MAVE)
)
CREATE TABLE XE
(
	BSXE CHAR(10),
	IDTUYENXE CHAR(5),
	IDLOAIXE CHAR(5),
	MOTA NCHAR(100)
	
	CONSTRAINT PK_XE PRIMARY KEY (BSXE)
)
CREATE TABLE TUYENXE 
(
	IDTUYENXE CHAR(5),
	TENTUYEN CHAR(20),
	NOIDI CHAR(20),
	NOIDEN CHAR(20),
	TONGTHOIGIAN INT,
	GIATIEN INT,
	KHOANGCACH FLOAT,

	CONSTRAINT PK_TUYENXE PRIMARY KEY (IDTUYENXE)
)
CREATE TABLE LOAIXE
(
	IDLOAIXE CHAR(5),
	TENLOAIXE CHAR(10),
	MOTA NCHAR(100),
	KICHTHUOCGHE_X INT,
	KICHTHUOCGHE_Y INT,
	LOAIGHE CHAR(10),
	SOLUONGHE INT,
	PHUPHI INT

	CONSTRAINT PK_LOAIXE PRIMARY KEY(IDLOAIXE)
)

ALTER TABLE VEXE 
ADD
	CONSTRAINT FK_VX_KH
	FOREIGN KEY(MAKH)
	REFERENCES KHACHHANG,

	CONSTRAINT FK_VX_XE
	FOREIGN KEY(BIENSOXE)
	REFERENCES XE

ALTER TABLE XE 
ADD
	CONSTRAINT FK_XE_TX
	FOREIGN KEY(IDTUYENXE)
	REFERENCES TUYENXE,

	CONSTRAINT FK_XE_LX
	FOREIGN KEY(IDLOAIXE)
	REFERENCES LOAIXE